---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: flake

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: write

jobs:
  flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Install nix
        id: nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30

      - name: Update flake
        id: flake
        run: nix flake update

      - name: Source rebase
        id: rebase
        run: git pull --autostash --rebase

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: flake.lock
          message: "chore(flake): updated lockfile [skip ci]"
          push: true
          commit: --signoff

...
